/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package componente;

/**
 *
 * @author alumno
 */
public class Componente extends javax.swing.JPanel {
    private String tipo_validacion;
    private boolean correcto;

    /**
     * Creates new form Componente
     */
    public Componente() {
        initComponents();
        correcto = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        text = new javax.swing.JTextField();
        error = new javax.swing.JLabel();

        text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(error, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(error)
                    .addComponent(text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFocusLost
        // TODO add your handling code here:
        String campo = text.getText();
        switch(tipo_validacion){
            case "TLF":
                if (campo.length() == 9) {
                    try{
                        Integer.parseInt(campo);
                        error.setText("Bien :)");
                        correcto = true;
                    }catch(Exception e){
                       error.setText("Error de " + tipo_validacion);
                       correcto = false;
                    }
                }else{
                    error.setText("Error de " + tipo_validacion);
                    correcto = false;
                }
                break;
                
            case "CP":
                if (campo.length() == 5) {
                    try{
                        Integer.parseInt(campo);
                        error.setText("Bien :)");
                        correcto = true;
                    }catch(Exception e){
                       error.setText("Error de " + tipo_validacion);
                       correcto = false;
                    }
                }else{
                    error.setText("Error de " + tipo_validacion);
                    correcto = false;
                }
                break;
                
            default:
                error.setText("Tipo no valido");
                correcto = false;
                break;     
        }
    }//GEN-LAST:event_textFocusLost

    public String getTipo_validacion() {
        return tipo_validacion;
    }

    public void setTipo_validacion(String tipo_validacion) {
        this.tipo_validacion = tipo_validacion;
    }

    public boolean isCorrecto() {
        return correcto;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel error;
    private javax.swing.JTextField text;
    // End of variables declaration//GEN-END:variables
}
